name: authmeengine
version: '1.0-SNAPSHOT'
main: eu.mrlubau.authmeengine.Authme_engine
api-version: '1.20'
channels:
  - BungeeCord
  - lobby
  - authme
commands:
  setspawn:
    description: Sets the place where people spawn after connecting
  engine:
    description: Lists plugin data
  engine-reload:
    description: auth commands
  register:
    description: create account
  login:
    description: login to your account
  autorizace:
    description: Autorizuje hrace
  edit:
    description: Enable edit mode